# Generated by Django 4.1.2 on 2022-10-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20220803_1339'),
        ('usuarios', '0003_auto_20220820_1852'),
    ]

    operations = [
    ]
